### ISSUE TITLE
msmtp: account default not found: no configuration file available

### ISSUE THREAD

**Issue by stoically** [crazy-max/docker-msmtpd#41]
#### Steps to reproduce this issue

1. Start docker container
2. Try to send an email

#### Expected behaviour

Sending E-Mail works.

#### Actual behaviour

Sending E-Mail fails and the log reports

> msmtp: account default not found: no configuration file available

Checking `msmtp --version` reports

> msmtp version 1.8.19
> Platform: x86_64-alpine-linux-musl
> System configuration file name: /usr/etc/msmtprc
> User configuration file name: /root/.msmtprc

But the docker-msmtpd init files create the config at `/etc/msmtprc`.

Workaround: `docker exec <container-name> bash -c "ln -s /etc/msmtprc /usr/etc/msmtprc"`

### Configuration

* docker hub tag: 1.8.19
* Docker version (type `docker --version`) : 20.10.12
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.10
* System info (type `uname -a`) : 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 GNU/Linux
* Include all necessary configuration files : Only ENV variable configuration:

```
        env:
          TZ: "Europe/Berlin"
          SMTP_HOST: "{{ mailcow_smtp_host }}"
          SMTP_PORT: "{{ mailcow_smtp_port | string }}"
          SMTP_STARTTLS: "on"
          SMTP_TLS: "on"
          SMTP_AUTH: "on"
          SMTP_USER: "{{ mailcow_username }}"
          SMTP_PASSWORD: "{{ mailcow_password }}"
          SMTP_FROM: "noreply@{{ main_domain }}"
          SMTP_TLS_CHECKCERT: "off"
```

### Logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing... 
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing... 
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing... 
Setting timezone to Europe/Berlin...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing... 
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] ~-socklog: executing... 
[cont-init.d] ~-socklog: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
msmtp: account default not found: no configuration file available
```

Thanks for your work on this!
